name: 🐛 Bug Report
description: バグの報告を行います
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: バグの概要
      description: バグの内容と期待する動作を簡潔に説明してください。
      placeholder: 〇〇をすると△△になるが、□□になってほしい
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 再現手順
      description: バグを再現する手順を明記してください。
      placeholder: |
        1. 〇〇ページに移動
        2. △△ボタンをクリック
        3. エラーが発生
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: 環境情報
      description: 使用している環境情報を入力してください（OS, ブラウザなど）
      placeholder: macOS 14.2 / Chrome 123
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: スクリーンショット（任意）
      description: エラー画面などがあれば添付してください。
      placeholder: 画像をここにドラッグ＆ドロップ

  - type: input
    id: contact
    attributes:
      label: 連絡先（任意）
      description: 必要であればGitHubユーザー名や連絡方法を記載してください。
